version: "3.8"

services:
  nginx:
    build: .
    container_name: mynginx
    ports:
      - "8080:80"
    volumes:
      - "/home/28112/Desktop/Учёба/Semestr 8/DevOps/lab1/static:/var/www/html:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    restart: unless-stopped